# Generated by Django 5.1.1 on 2024-12-14 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_recipe_portions_alter_recipe_time_to_cook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Preparation must have at least 3 letters!')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quick_description',
            field=models.CharField(default='No Description', max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Description must have at least 3 letters!')]),
            preserve_default=False,
        ),
    ]
