# Generated by Django 5.1.1 on 2024-12-14 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_recipe_preparation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customunit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customunit',
            name='custom_convert_to_base_rate',
            field=models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001, 'Base rate must be at least 0.001.')]),
        ),
    ]
