# Generated by Django 5.1.1 on 2024-12-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_customunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='common/default-recipe-image.png', null=True, upload_to='recipes-images/'),
        ),
    ]
