# Generated by Django 5.1.1 on 2024-12-16 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0002_profile'),
        ('inventory', '0012_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipescollection',
            name='profile',
        ),
        migrations.AddField(
            model_name='recipescollection',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_collections', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, 'Quantity must be at least 0.01.')]),
        ),
        migrations.AlterField(
            model_name='recipescollection',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3, 'Recipe collection name must be at least 3 characters.')]),
        ),
        migrations.CreateModel(
            name='SavedRecipesCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipes_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='inventory.recipescollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_collections', to='accounts.profile')),
            ],
        ),
    ]
