# Generated by Django 5.1.1 on 2024-12-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_recipescollection_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipescollection',
            old_name='owner',
            new_name='created_by',
        ),
    ]
