# Generated by Django 5.1.1 on 2024-12-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_owner_recipescollection_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
