# Generated by Django 5.1.1 on 2024-12-18 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_to_cook',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Time to cook must be set at least 0 minute!'), django.core.validators.MaxValueValidator(1440, 'Time to cook can be set at maximum 1440 minutes!')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_to_prepare',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Time to prepare must be set at least 0 minute!'), django.core.validators.MaxValueValidator(1440, 'Time to prepare can be set at maximum 1440 minutes!')]),
        ),
    ]
