# Generated by Django 5.1.1 on 2024-12-18 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_recipe_time_to_cook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, 'Quantity must be at least 0.01.'), django.core.validators.MaxValueValidator(1000.01, 'Quantity must be lower than 1000!')]),
        ),
    ]
