# Generated by Django 5.1.1 on 2024-12-18 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_recipeproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customunit',
            name='custom_convert_to_base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, 'Base rate must be at least 0.01.')]),
        ),
    ]
